//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontMemoire3Tier.ServiceMemoire {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/MetierMemoire")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Memoire", Namespace="http://schemas.datacontract.org/2004/07/MetierMemoire.Model")]
    [System.SerializableAttribute()]
    public partial class Memoire : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AnneeMemoireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionMemoireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDMemoireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SujetMemoireField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AnneeMemoire {
            get {
                return this.AnneeMemoireField;
            }
            set {
                if ((this.AnneeMemoireField.Equals(value) != true)) {
                    this.AnneeMemoireField = value;
                    this.RaisePropertyChanged("AnneeMemoire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescriptionMemoire {
            get {
                return this.DescriptionMemoireField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionMemoireField, value) != true)) {
                    this.DescriptionMemoireField = value;
                    this.RaisePropertyChanged("DescriptionMemoire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDMemoire {
            get {
                return this.IDMemoireField;
            }
            set {
                if ((this.IDMemoireField.Equals(value) != true)) {
                    this.IDMemoireField = value;
                    this.RaisePropertyChanged("IDMemoire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SujetMemoire {
            get {
                return this.SujetMemoireField;
            }
            set {
                if ((object.ReferenceEquals(this.SujetMemoireField, value) != true)) {
                    this.SujetMemoireField = value;
                    this.RaisePropertyChanged("SujetMemoire");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MemoireModel", Namespace="http://schemas.datacontract.org/2004/07/MetierMemoire.Model")]
    [System.SerializableAttribute()]
    public partial class MemoireModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AnneeMemoireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SujetMemoireField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AnneeMemoire {
            get {
                return this.AnneeMemoireField;
            }
            set {
                if ((this.AnneeMemoireField.Equals(value) != true)) {
                    this.AnneeMemoireField = value;
                    this.RaisePropertyChanged("AnneeMemoire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SujetMemoire {
            get {
                return this.SujetMemoireField;
            }
            set {
                if ((object.ReferenceEquals(this.SujetMemoireField, value) != true)) {
                    this.SujetMemoireField = value;
                    this.RaisePropertyChanged("SujetMemoire");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMemoire.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        FrontMemoire3Tier.ServiceMemoire.CompositeType GetDataUsingDataContract(FrontMemoire3Tier.ServiceMemoire.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<FrontMemoire3Tier.ServiceMemoire.CompositeType> GetDataUsingDataContractAsync(FrontMemoire3Tier.ServiceMemoire.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllMemoire", ReplyAction="http://tempuri.org/IService1/GetAllMemoireResponse")]
        FrontMemoire3Tier.ServiceMemoire.Memoire[] GetAllMemoire();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllMemoire", ReplyAction="http://tempuri.org/IService1/GetAllMemoireResponse")]
        System.Threading.Tasks.Task<FrontMemoire3Tier.ServiceMemoire.Memoire[]> GetAllMemoireAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMemoire", ReplyAction="http://tempuri.org/IService1/GetMemoireResponse")]
        FrontMemoire3Tier.ServiceMemoire.Memoire GetMemoire(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMemoire", ReplyAction="http://tempuri.org/IService1/GetMemoireResponse")]
        System.Threading.Tasks.Task<FrontMemoire3Tier.ServiceMemoire.Memoire> GetMemoireAsync(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddMemoire", ReplyAction="http://tempuri.org/IService1/AddMemoireResponse")]
        bool AddMemoire(FrontMemoire3Tier.ServiceMemoire.Memoire memo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddMemoire", ReplyAction="http://tempuri.org/IService1/AddMemoireResponse")]
        System.Threading.Tasks.Task<bool> AddMemoireAsync(FrontMemoire3Tier.ServiceMemoire.Memoire memo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMemoireList", ReplyAction="http://tempuri.org/IService1/GetMemoireListResponse")]
        FrontMemoire3Tier.ServiceMemoire.Memoire[] GetMemoireList(FrontMemoire3Tier.ServiceMemoire.MemoireModel memo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMemoireList", ReplyAction="http://tempuri.org/IService1/GetMemoireListResponse")]
        System.Threading.Tasks.Task<FrontMemoire3Tier.ServiceMemoire.Memoire[]> GetMemoireListAsync(FrontMemoire3Tier.ServiceMemoire.MemoireModel memo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditMemoire", ReplyAction="http://tempuri.org/IService1/EditMemoireResponse")]
        bool EditMemoire(FrontMemoire3Tier.ServiceMemoire.Memoire memo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditMemoire", ReplyAction="http://tempuri.org/IService1/EditMemoireResponse")]
        System.Threading.Tasks.Task<bool> EditMemoireAsync(FrontMemoire3Tier.ServiceMemoire.Memoire memo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteMemoire", ReplyAction="http://tempuri.org/IService1/DeleteMemoireResponse")]
        bool DeleteMemoire(FrontMemoire3Tier.ServiceMemoire.Memoire memo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteMemoire", ReplyAction="http://tempuri.org/IService1/DeleteMemoireResponse")]
        System.Threading.Tasks.Task<bool> DeleteMemoireAsync(FrontMemoire3Tier.ServiceMemoire.Memoire memo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : FrontMemoire3Tier.ServiceMemoire.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<FrontMemoire3Tier.ServiceMemoire.IService1>, FrontMemoire3Tier.ServiceMemoire.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public FrontMemoire3Tier.ServiceMemoire.CompositeType GetDataUsingDataContract(FrontMemoire3Tier.ServiceMemoire.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<FrontMemoire3Tier.ServiceMemoire.CompositeType> GetDataUsingDataContractAsync(FrontMemoire3Tier.ServiceMemoire.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public FrontMemoire3Tier.ServiceMemoire.Memoire[] GetAllMemoire() {
            return base.Channel.GetAllMemoire();
        }
        
        public System.Threading.Tasks.Task<FrontMemoire3Tier.ServiceMemoire.Memoire[]> GetAllMemoireAsync() {
            return base.Channel.GetAllMemoireAsync();
        }
        
        public FrontMemoire3Tier.ServiceMemoire.Memoire GetMemoire(System.Nullable<int> id) {
            return base.Channel.GetMemoire(id);
        }
        
        public System.Threading.Tasks.Task<FrontMemoire3Tier.ServiceMemoire.Memoire> GetMemoireAsync(System.Nullable<int> id) {
            return base.Channel.GetMemoireAsync(id);
        }
        
        public bool AddMemoire(FrontMemoire3Tier.ServiceMemoire.Memoire memo) {
            return base.Channel.AddMemoire(memo);
        }
        
        public System.Threading.Tasks.Task<bool> AddMemoireAsync(FrontMemoire3Tier.ServiceMemoire.Memoire memo) {
            return base.Channel.AddMemoireAsync(memo);
        }
        
        public FrontMemoire3Tier.ServiceMemoire.Memoire[] GetMemoireList(FrontMemoire3Tier.ServiceMemoire.MemoireModel memo) {
            return base.Channel.GetMemoireList(memo);
        }
        
        public System.Threading.Tasks.Task<FrontMemoire3Tier.ServiceMemoire.Memoire[]> GetMemoireListAsync(FrontMemoire3Tier.ServiceMemoire.MemoireModel memo) {
            return base.Channel.GetMemoireListAsync(memo);
        }
        
        public bool EditMemoire(FrontMemoire3Tier.ServiceMemoire.Memoire memo) {
            return base.Channel.EditMemoire(memo);
        }
        
        public System.Threading.Tasks.Task<bool> EditMemoireAsync(FrontMemoire3Tier.ServiceMemoire.Memoire memo) {
            return base.Channel.EditMemoireAsync(memo);
        }
        
        public bool DeleteMemoire(FrontMemoire3Tier.ServiceMemoire.Memoire memo) {
            return base.Channel.DeleteMemoire(memo);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteMemoireAsync(FrontMemoire3Tier.ServiceMemoire.Memoire memo) {
            return base.Channel.DeleteMemoireAsync(memo);
        }
    }
}
